/* eslint-disable max-lines-per-function */

import { IColumn } from '../../../../shared/interfaces/column.interface';

export class DuplicatesTableColumns {
  private static columns: IColumn[];

  static getColumns(): IColumn[] {
    this.columns = [
      {
        field: 'vendorCustomerCode',
        header: 'Vendor/Customer Code',
        style: { 'min-width': '12rem', 'max-width': '12rem' },
        filterable: true,
        filterMultiselect: false,
        filterField: 'vendorCustomerCode',
        frozen: true,
        sortable: true,
      },
      {
        field: 'origin',
        header: 'Origin',
        sortable: true,
        filterable: true,
        style: { 'min-width': '7rem', 'max-width': '7rem' },
        filterField: 'selectedOrigin',
        filterMultiselect: true,
        frozen: true,
      },
      {
        field: 'cfinCode',
        header: 'CFIN Code',
        filterField: 'cfinCode',
        style: { 'min-width': '10rem', 'max-width': '10rem' },
        class: 'numeric-data',
        sortable: true,
        filterable: true,
        filterMultiselect: false,
        frozen: true,
      },
      {
        field: 'name1',
        header: 'Name 1',
        style: { 'min-width': '10rem', 'max-width': '10rem' },
        sortable: true,
        filterable: true,
        filterMultiselect: false,
        filterField: 'name1',
        frozen: true,
        editable: true
      },
      {
        field: 'name2',
        header: 'Name 2',
        filterField: 'name2',
        sortable: true,
        filterable: true,
        filterMultiselect: false,
        style: { 'min-width': '7rem', 'max-width': '7rem' },
        frozen: true,
        editable: true
      },
      {
        field: 'street',
        header: 'Street',
        filterable: true,
        sortable: true,
        filterMultiselect: false,
        style: { 'min-width': '7rem', 'max-width': '7rem' },
        filterField: 'street',
        frozen: true,
        editable: true
      },
      {
        field: 'vatRegistrationNumber',
        header: 'VAT Registration Number',
        style: { 'min-width': '12rem', 'max-width': '12rem' },
        class: 'numeric-data',
        sortable: true,
        filterable: true,
        filterMultiselect: false,
        filterField: 'vatRegistrationNumber',
        frozen: true,
        editable: true
      },
      {
        field: 'vatTaxComparable',
        header: 'VAT/TAX Comparable',
        style: { 'min-width': '12rem', 'max-width': '12rem' },
        class: 'numeric-data',
        sortable: true,
        filterable: true,
        editable: true,
        filterField: 'vatTaxComparable',
        frozen: true,
      },
      {
        field: 'category',
        header: 'Category',
        style: { 'min-width': '10rem', 'max-width': '10rem' },
        sortable: true,
        filterable: true,
        filterMultiselect: true,
        filterField: 'selectedCategory',
        frozen: true,
      },
      {
        field: 'bpGrouping',
        header: 'BP Grouping',
        style: { 'min-width': '7rem', 'max-width': '7rem' },
        filterable: true,
        filterMultiselect: true,
        sortable: true,
        filterField: 'selectedBpGrouping',
        frozen: true,
      },
      {
        field: 'accountGroup',
        header: 'Account Group',
        style: { 'min-width': '7rem', 'max-width': '7rem' },
        sortable: true,
        filterable: true,
        filterMultiselect: true,
        class: 'numeric-data',
        filterField: 'selectedAccountGroup',
        frozen: true,
      },
      {
        field: 'taxNumber1',
        header: 'Tax Number 1',
        class: 'numeric-data',
        sortable: true,
        filterable: true,
        filterMultiselect: false,
        filterField: 'taxNumber1',
      },
      {
        field: 'searchTerm',
        header: 'Search Term',
        sortable: true,
        filterable: true,
        filterField: 'searchTerm',
        filterMultiselect: false,
      },
      {
        field: 'country',
        header: 'Country',
        filterField: 'country',
        filterable: true,
        filterMultiselect: false,
        sortable: true,
      },
      {
        field: 'city',
        header: 'City',
        sortable: true,
        filterMultiselect: false,
        filterable: true,
        filterField: 'city',
      },
      {
        field: 'poBox',
        filterable: true,
        header: 'PO Box',
        sortable: true,
        filterMultiselect: false,
        filterField: 'poBox',
      },
      {
        field: 'postalCode',
        header: 'Postal Code',
        filterMultiselect: false,
        sortable: true,
        filterable: true,
        filterField: 'postalCode',
      },
      {
        field: 'region',
        filterMultiselect: false,
        header: 'Region',
        sortable: true,
        filterable: true,
        filterField: 'region',
      },
      {
        field: 'district',
        filterField: 'district',
        header: 'District',
        filterable: true,
        sortable: true,
        filterMultiselect: false,
      },
      {
        field: 'vendor',
        header: 'Vendor',
        sortable: true,
        filterable: true,
        filterMultiselect: true,
        filterField: 'selectedVendor',
      },
      {
        field: 'customer',
        header: 'Customer',
        filterable: true,
        filterMultiselect: true,
        filterField: 'selectedCustomer',
        sortable: true,
      },
      {
        field: 'title',
        header: 'Title',
        sortable: true,
        filterMultiselect: false,
        filterable: true,
        filterField: 'title',
      },
      {
        field: 'group',
        header: 'Group',
        filterMultiselect: false,
        sortable: true,
        filterField: 'group',
        filterable: true,
      },
      {
        field: 'language',
        header: 'Language',
        sortable: true,
        filterable: true,
        filterMultiselect: false,
        filterField: 'language',
      },
      {
        field: 'telephone1',
        header: 'Telephone 1',
        class: 'numeric-data',
        filterMultiselect: false,
        sortable: true,
        filterable: true,
        filterField: 'telephone1',
      },
      {
        field: 'faxNumber',
        header: 'Fax Number',
        class: 'numeric-data',
        sortable: true,
        filterable: true,
        filterMultiselect: false,
        filterField: 'faxNumber',
      },
      {
        field: 'url',
        header: 'URL',
        sortable: true,
        filterable: true,
        filterField: 'url',
        filterMultiselect: false,
      },
      {
        field: 'tradingPartner',
        header: 'Trading Partner',
        sortable: true,
        filterable: true,
        filterMultiselect: false,
        filterField: 'tradingPartner',
      },
      {
        field: 'oneTimeAcc',
        header: 'OneTimeACC',
        sortable: true,
        filterable: true,
        filterMultiselect: true,
        filterField: 'selectedOneTimeAcc',
      },
      {
        field: 'retrievedOn',
        header: 'Retrieved On',
        filterField: 'retrievedOn',
        class: 'numeric-data',
        sortable: true,
        filterable: true,
        filterMultiselect: false,
        datepicker: true,
      },
      {
        field: 'exportedBy',
        header: 'Exported By',
        sortable: true,
        filterable: true,
        filterMultiselect: false,
        filterField: 'exportedBy',
      },
      {
        field: 'exportedOn',
        header: 'Exported On',
        class: 'numeric-data',
        filterMultiselect: false,
        sortable: true,
        filterable: true,
        datepicker: true,
        filterField: 'exportedOn',
      },
      {
        field: 'updatedBy',
        header: 'Updated By',
        sortable: true,
        filterable: true,
        filterMultiselect: false,
        filterField: 'updatedBy',
      },
      {
        field: 'updatedOn',
        header: 'Update On',
        sortable: true,
        class: 'numeric-data',
        filterable: true,
        filterField: 'updatedOn',
        filterMultiselect: false,
        datepicker: true,
      },
      {
        field: 'comment',
        header: 'Comment',
        sortable: true,
        filterable: true,
        filterMultiselect: false,
        filterField: 'comment',
      }
    ];

    return this.columns;
  }
}
